# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17
        java-package: jdk
    - name: Checkout core
      run: git clone --depth=50 --branch=develop https://github.com/informatici/openhospital-core.git openhospital-core
    - name: Install core
      run: cd openhospital-core && mvn install -DskipTests=true && cd ..
    - name: Build GUI with Maven
      run: mvn -B package --file pom.xml
